#!/usr/bin/env bash
# check_neurips_paper.sh — OPTIONAL NeurIPS-readiness preflight for a LaTeX paper.
#
# Complements check_paper.sh (which is the hard build/integrity gate). This one
# is ADVISORY: it builds the paper, measures it, and compares against an
# empirical profile of ~20 NeurIPS/ICML/ICLR award/oral/spotlight papers
# (tools/neurips_profile.json, regenerated by build_neurips_profile.sh), plus a
# few fixed bars and content heuristics. Every finding is a soft [advisory];
# top papers vary widely, so treat these as prompts, not failures.
#
# Usage: check_neurips_paper.sh <path/to/main.tex>
# Exit: 0 if no advisories, else 1 (so it can gate if you want — but it is
#   advisory by design).

set -u
MAIN="${1:-}"
[ -n "$MAIN" ] || { echo "usage: check_neurips_paper.sh <main.tex>"; exit 2; }
[ -f "$MAIN" ] || { echo "FAIL: '$MAIN' not found"; exit 2; }
HERE="$(cd "$(dirname "$0")" && pwd)"
PROFILE="$HERE/neurips_profile.json"
[ -f "$PROFILE" ] || { echo "FAIL: $PROFILE missing (run build_neurips_profile.sh first)"; exit 2; }
DIR=$(cd "$(dirname "$MAIN")" && pwd); BASE=$(basename "$MAIN" .tex); cd "$DIR" || exit 2

adv=0
ADV(){ echo "  [advisory] $1"; adv=$((adv+1)); }
OK(){ echo "  [ ok ]     $1"; }
g(){ jq -r "$1" "$PROFILE"; }   # read a profile value

srcfiles(){ echo "$BASE.tex"; awk '{s=$0; while(match(s,/\\(input|include)\{[^}]+\}/)){t=substr(s,RSTART,RLENGTH);sub(/^\\(input|include)\{/,"",t);sub(/\}$/,"",t);if(t!~/\.tex$/)t=t".tex";print t;s=substr(s,RSTART+RLENGTH)}}' "$BASE.tex" 2>/dev/null; }
ALLSRC(){ for f in $(srcfiles); do [ -f "$f" ] && cat "$f"; done; }

echo "== build $BASE.tex =="
rm -f "$BASE.aux" "$BASE.bbl" "$BASE.blg" "$BASE.log" 2>/dev/null
pdflatex -interaction=nonstopmode "$BASE.tex" >/dev/null 2>&1
bibtex "$BASE" >/dev/null 2>&1
pdflatex -interaction=nonstopmode "$BASE.tex" >/dev/null 2>&1
pdflatex -interaction=nonstopmode "$BASE.tex" >/dev/null 2>&1

# --- measure target (PDF-based, same as the profile) ---
PAGES=$(pdfinfo "$BASE.pdf" 2>/dev/null | awk '/^Pages/{print $2}'); PAGES=${PAGES:-0}
pdftotext "$BASE.pdf" "$BASE.__txt" 2>/dev/null
FIGS=$(awk 'BEGIN{m=0}/^Figure [0-9]+[:.]/{n=$2+0;if(n>m)m=n}END{print m}' "$BASE.__txt" 2>/dev/null); FIGS=${FIGS:-0}
TABS=$(awk 'BEGIN{m=0}/^Table [0-9]+[:.]/{n=$2+0;if(n>m)m=n}END{print m}' "$BASE.__txt" 2>/dev/null); TABS=${TABS:-0}
# main-body pages = page where the References header starts (form-feed delimited,
# de-spaced to handle letter-spaced "R EFERENCES"); same method as the profile.
MBPAGES=$(awk 'BEGIN{pg=1;refpg=0}{n=gsub(/\f/,"\f");line=$0;gsub(/\f/,"",line);d=line;gsub(/ /,"",d);if(refpg==0&&tolower(d)=="references")refpg=pg;pg+=n}END{print (refpg>0?refpg:0)}' "$BASE.__txt" 2>/dev/null); MBPAGES=${MBPAGES:-0}
rm -f "$BASE.__txt"
REFS=$([ -f "$BASE.bbl" ] && awk '/\\bibitem/{c++}END{print c+0}' "$BASE.bbl" || echo 0)
CITES=$(ALLSRC | awk '{while(match($0,/\\cite[a-z]*\{/)){c++;$0=substr($0,RSTART+RLENGTH)}}END{print c+0}')
APPDX=$(ALLSRC | awk '/\\appendix([^a-zA-Z]|$)/{f=1} END{print f+0}')

echo "== structure vs award papers (profile: $(g '.n_papers') papers) =="
echo "  target: total=${PAGES}pp main_body=${MBPAGES}pp figures=$FIGS tables=$TABS refs=$REFS cites=$CITES appendix=$([ "$APPDX" -gt 0 ] && echo yes || echo no)"

# main-body pages = the venue page limit, NOT the appendix-inflated total
mbmin=$(g '.main_body_pages.min'); mbmax=$(g '.main_body_pages.max'); mbmed=$(g '.main_body_pages.median')
if [ "$MBPAGES" -eq 0 ]; then ADV "no References section located — main-body length unmeasured"
elif [ "$MBPAGES" -gt "$mbmax" ]; then ADV "main body ($MBPAGES pp) over award-paper max ($mbmax pp) — likely past the venue page limit; move material to the appendix"
elif [ "$MBPAGES" -lt "$mbmin" ]; then ADV "main body ($MBPAGES pp) under award-paper min ($mbmin pp) — under-developed"
else OK "main body ($MBPAGES pp) within award range [$mbmin-$mbmax], median $mbmed"; fi
# appendix presence
appf=$(g '.has_appendix_frac'); appp=$(awk -v k="$appf" 'BEGIN{print int(k*100)}')
if [ "$APPDX" -gt 0 ]; then OK "appendix present (${appp}% of award papers have one)"
else ADV "no \\appendix — ${appp}% of award papers include one (proofs, extra results, repro details)"; fi
# figures
fmin=$(g '.figures.min'); fmed=$(g '.figures.median')
if [ "$FIGS" -lt "$fmin" ]; then ADV "figures ($FIGS) below award-paper min ($fmin); median $fmed — top papers are figure-rich"
else OK "figures ($FIGS) >= award-paper min ($fmin); median $fmed"; fi
# tables
tmed=$(g '.tables.median')
if [ "$TABS" -lt "$tmed" ]; then ADV "tables ($TABS) below award-paper median ($tmed)"
else OK "tables ($TABS) >= award-paper median ($tmed)"; fi
# references (fixed advisory bar; PDF ref-count norms not scraped)
if [ "$REFS" -lt 25 ]; then ADV "references ($REFS) is low — strong ML papers typically cite 30+ works"
else OK "references ($REFS) >= 25"; fi

echo "== expected sections (present in >50% of award papers) =="
LSRC=$(ALLSRC | tr 'A-Z' 'a-z')
has(){ printf '%s' "$LSRC" | awk -v p="$1" 'index($0,p){f=1}END{exit !f}'; }
chk_sec(){ if has "$2"; then OK "$1 present"; else ADV "$1 section appears missing (in $(awk -v k="$3" 'BEGIN{print int(k*100)}')% of award papers)"; fi; }
chk_sec "Related Work"  "related work"  "$(g '.section_freq.related_work')"
chk_sec "Experiments"   "experiment"    "$(g '.section_freq.experiments')"
chk_sec "Ablation"      "ablation"      "$(g '.section_freq.ablation')"
chk_sec "Limitations"   "limitation"    "$(g '.section_freq.limitations')"
chk_sec "Conclusion"    "conclusion"    "$(g '.section_freq.conclusion')"

echo "== content heuristics =="
# results report variance / CIs
if [ "$TABS" -gt 0 ]; then
  if printf '%s' "$LSRC" | awk '/\\pm|±|confidence interval|\\bci\\b|std\\.|stddev|standard deviation|error bar|±/{f=1}END{exit !f}'; then OK "results report variance/CIs (\\pm / CI / std found)"
  else ADV "has tables but no variance/CI markers (\\pm, CI, std, error bars) — reviewers expect uncertainty"; fi
fi
# reproducibility / code statement
if printf '%s' "$LSRC" | awk '/github\.com|code is available|we release|reproducib|anonymous|supplementary material|our code/{f=1}END{exit !f}'; then OK "reproducibility/code statement present"
else ADV "no reproducibility/code-availability statement found (github, 'we release', 'code is available')"; fi
# claim density (very rough)
if [ "$CITES" -lt 20 ]; then ADV "few in-text citations ($CITES \\cite calls) — claims may be under-grounded"; else OK "in-text citations: $CITES \\cite calls"; fi

echo "== section lengths (target .tex \\section vs award-paper medians) =="
# Per-section word counts from the source (main body before \appendix / back matter).
# ROW = display line; BUK = canonical-bucket word count; SUM = main-body totals.
SECT=$(ALLSRC | awk '
  function bucket(n,  l){ l=tolower(n);
    if(l ~ /introduction/) return "introduction";
    if(l ~ /related|prior work/) return "related_work";
    if(l ~ /experiment|empirical|evaluation|results/) return "experiments";
    if(l ~ /conclusion|discussion/) return "conclusion"; return "" }
  function endmain(n,  l){ l=tolower(n); return (l ~ /references|acknowledg|broader impact|author contribution|appendix|supplementary/) }
  function flush(   b){ if(cur!=""){ printf "ROW\t%s\t%d\t%d\n", cur, w, inapp;
      if(!inapp){ mainw+=w; if(w>mxw){mxw=w; mxs=cur}; b=bucket(cur); if(b!="") printf "BUK\t%s\t%d\n", b, w } } }
  /\\appendix([^a-zA-Z]|$)/ { flush(); inapp=1; cur=""; w=0; next }
  /\\section\*?\{/ { flush(); s=$0; match(s,/\\section\*?\{[^}]*\}/); h=substr(s,RSTART,RLENGTH); sub(/\\section\*?\{/,"",h); sub(/\}.*/,"",h); if(endmain(h)) inapp=1; cur=h; w=0; next }
  cur!="" { t=$0; gsub(/%.*/,"",t); gsub(/\\[a-zA-Z]+\*?/,"",t); gsub(/[{}$&~^_]/," ",t); w+=split(t,a," ") }
  END{ flush(); printf "SUM\t%d\t%d\t%s\n", mainw, mxw, mxs }')
printf '%s\n' "$SECT" | awk -F'\t' '$1=="ROW"{ printf "  %-34.34s %5d words%s\n", $2, $3, ($4=="1"?"  [appendix/back-matter]":"") }'
for b in introduction related_work experiments conclusion; do
  med=$(g ".section_words.$b.median_words"); [ "$med" = "null" ] && continue
  tw=$(printf '%s\n' "$SECT" | awk -F'\t' -v B="$b" '$1=="BUK"&&$2==B{s+=$3}END{print s+0}')
  [ "$tw" -eq 0 ] && continue   # section absent -> already covered by expected-sections check
  lbl=$(printf '%s' "$b" | tr '_' ' ')
  if [ "$tw" -lt "$(( med / 2 ))" ]; then ADV "$lbl is short ($tw words vs award median $med) — likely needs expansion"
  else OK "$lbl length $tw words (award median $med)"; fi
done
mainw=$(printf '%s\n' "$SECT" | awk -F'\t' '$1=="SUM"{print $2}'); mxw=$(printf '%s\n' "$SECT" | awk -F'\t' '$1=="SUM"{print $3}'); mxs=$(printf '%s\n' "$SECT" | awk -F'\t' '$1=="SUM"{print $4}')
if [ "${mainw:-0}" -gt 0 ] && [ "$(( mxw * 2 ))" -gt "$mainw" ]; then ADV "one section (\"$mxs\", $mxw w) is >50% of the $mainw-word main body — consider rebalancing"; fi

echo "== verdict =="
if [ "$adv" -eq 0 ]; then echo "OK — consistent with top-venue norms (no advisories)"; exit 0
else echo "$adv advisory item(s) — soft guidance vs NeurIPS/ICML/ICLR award papers, not hard failures"; exit 1; fi
